Concordium/concordium-rust-sdk

Cargo.toml
src/types/smart_contracts.rs

When working with smart contracts types and serialization from `concordium-contracts-common` is useful.
- Re-export `concordium-contracts-common`.
- Enable `derive-serde` feature on `concordium-contracts-common`.

Re-export concordium-contracts-common and enable derive-serde feature

---

src/types/transactions.rs

Fix serialization for `Payload::TransferToPublic`

Fix transfer to public serialization

---

src/types/transactions.rs

To be able to construct a update contract transaction the fields needs to be public

Make update contract payload fields public

---

src/endpoints.rs
src/types/basic.rs
src/types/queries.rs

With version 1.1 the node has a bit of an extended API.
This SDK will not work with node version 1.0, but that is obsolete soon so it does not make sense to spend time on backwards compatibility.

Support new node API.

---

Cargo.toml
src/types/basic.rs
src/types/mod.rs
src/types/transactions.rs

See https://github.com/Concordium/concordium-base/pull/76
Add functions for generating baker keys and constructing the relevant transactions payload with proofs of knowledge of the bakers secret keys.
- Add newtypes for the baker signing keys.
- Add `BakerKeyPairs` struct containing both the bakers secret and public keys.
- Add functions to construct `BakerKeysPayload` using a `BakerKeyPairs` struct.
- Extend `BakerKeysPayload` with a marker for whether the proofs are generated for adding or updating baker keys.

Add baker key functions

---

Cargo.toml
src/lib.rs
src/types/mod.rs

To update dependency to concordium-base and to remove some re-exports.
* Updated base dependency
* Remove re-exports of pedersen_scheme and elgamal since they are now re-exported by the id crate in concordium-base.

Update base dependency and remove some re-exports

---

src/types/mod.rs
src/types/transactions.rs

Ensure that the SDK serves the needs of the Rosetta implementation (WIP).
Add a function for getting the `TransactionType` of a `Payload` object (used [here](https://gitlab.com/Concordium/concordium-rosetta/-/blob/ab9de7480b0222e61816b5e8e4a2ec16d634029f/src/api/construction.rs#L449) for error reporting).

Add method for resolving TransactionType of a Payload

---

.github/workflows/docs.yaml
src/types/transactions.rs

Publish documentation on github pages since we cannot do it on crates as of yet since dependencies are not on crates.io.

Add a job to generate documentation.

---

CHANGELOG.md
Cargo.toml
src/types/basic.rs
src/types/mod.rs

Ensure that the SDK satisfy the needs of Rosetta.
* Derive `Display` on `AmountFraction`.
* Add comment to explain how to determine delegation pool of account referenced in `PaydayAccountReward`.
* Fix deserialization of `RewardsDataRaw`.

Updates for Rosetta needs

---

examples/block-stats.rs

Include transaction count for block stats. 
This can be a useful statistic and as such it is now included.
Included the transaction count per block when traversing the chain. 

Include transaction count for block stats.

---

examples/generator.rs

Add support for setting the amount to send in the generator example.
- Add an `--amount` command-line parameter to the generator example for providing the transfer amount.

Update generator example to support a transfer amount.

---

examples/v2_get_account_info.rs
examples/v2_get_account_list.rs
examples/v2_get_ancestors.rs
examples/v2_get_consensus_info.rs
examples/v2_get_finalized_blocks.rs
examples/v2_get_instance_list.rs
examples/v2_get_module_list.rs
examples/v2_get_module_source.rs
examples/v2_get_next_account_nonce.rs
examples/v2_get_next_account_sequence_number.rs
src/v2/generated.rs
src/v2/mod.rs

Support some of the new gRPC functions.
- Implement `get_next_account_sequence_number`, `get_consensus_info`, `get_module_list`, `get_module_source`, `get_instance_list` and `get_ancestors` in v2 client.

First round of gRPC api v2 functions

---

examples/v2_get_branches.rs
examples/v2_get_passive_delegators.rs
examples/v2_get_passive_delegators_reward_period.rs
examples/v2_get_pool_delegators.rs
examples/v2_get_pool_delegators_reward_period.rs
src/types/mod.rs
src/types/queries.rs
src/v2/generated.rs
src/v2/mod.rs

Depends on https://github.com/Concordium/concordium-grpc-api/pull/17
Related to https://github.com/Concordium/concordium-node/issues/433
- Support `GetPoolDelegators`, `GetPoolDelegatorsRewardPeriod`, `GetPassiveDelegators`, `GetPassiveDelegatorsRewardPeriod` and `GetBranches` in gRPC API v2.

Add getters for delegators in client v2

---

examples/v2_get_account_non_finalized_transactions.rs
examples/v2_get_anonymity_revokers.rs
examples/v2_get_election_info.rs
examples/v2_get_identity_providers.rs
src/v2/generated.rs
src/v2/mod.rs

Implement more of API v2.
Related issue https://github.com/Concordium/concordium-node/issues/433.
Depends on https://github.com/Concordium/concordium-node/pull/521.
- `GetElectionInfo`, `GetIdentityProvidersV2`, `GetAnonymityRevokers` and `GetAccountNonFinalizedTransactions`.

API v2 Getters for info about election, IP, AR and nonfinal tx

---

CHANGELOG.md
src/cis2/mod.rs
src/types/mod.rs
src/types/smart_contracts.rs

Add more functionality to the CIS2Contract struct.
Allow more ergonomic use in the case of single query, and add dry-run functionality.

Add a number of CIS2 related improvements.

---

src/v2/mod.rs

When querying a node for anything related to protocol version 4 baking/delegation state, the corresponding client methods return undocumented errors for blocks produced prior to protocol version 4.

Document errors happening due to block protocol version

---

CHANGELOG.md
src/v2/mod.rs

On suggestion from @abizjak , this adds a method to `v2::Client` which checks if a block is a payday block or not.

Add method to v2 client for identifying payday blocks

---

.github/workflows/build-and-test.yaml
.gitignore
Cargo.toml
README.md
build.rs
examples/basic-test.rs
src/generated_types.rs
src/lib.rs
src/types/smart_contracts.rs
src/v1/generated/concordium.rs
src/v2/generated.rs
src/v2/generated/concordium.v2.rs
src/v2/mod.rs

This achieves two things - the user does not need a protobuf compiler to use the
SDK. - we decouple the version of the api in concordium-base from version used
in the SDK. The upstream version has changes which we don't want to expose in
the SDK yet until they are available in the node.
- Commit generated proto-files to the repository so that users don't have to have protobuf installed.
- Add documentation related to this.
- Add a new internal feature `generate-protos` that can be used to regenerate Rust sources from protobuf schemas.

Commit generated protos

---

Cargo.toml
examples/protocol-updates.rs
src/types/mod.rs

Propagate changes from https://github.com/Concordium/concordium-base/pull/337
Remove obsolete comment from Cargo.toml file. MSRV is now 1.60.

Propagate changes to rust-src/concordium-base restructuring.

---

examples/block-stats.rs
examples/generator.rs
src/v2/conversions.rs

Change the block-stats script so that it stops only after reaching the given time.
Also migrates the block stats to V2 interface.
Additionally make the conversion of timestamp to datetime fallible.

Revise block stats so that it will only stop after a designated time.

---

.github/workflows/build-and-test.yaml
src/types/mod.rs

Update Rust fmt to `2023-04-01` to match other Rust repos.
Depends on: https://github.com/Concordium/concordium-base/pull/369
- Update version in CI jobs
- Update base dependency
- Fix minor formatting issues

Update Rust fmt to `2023-04-01`

---

CHANGELOG.md
examples/v2_update_exchange_rate.rs
src/types/queries.rs
src/v1/generated/concordium.rs
src/v2/conversions.rs
src/v2/generated/concordium.v2.rs
src/v2/mod.rs
src/v2/proto_schema_version.rs

Closes #93.
Depends on https://github.com/Concordium/concordium-base/pull/372 and https://github.com/Concordium/concordium-contracts-common/pull/85.
- Extend enum `PendingUpdateEffect` with variants for protocol version 6.
- Build gRPC API.
- Add converters for new types introduced in the GRPC

Support latest grpc api version with protocol version 6 types

---

CHANGELOG.md
examples/v2_update_exchange_rate.rs
src/types/mod.rs
src/types/queries.rs
src/v1/generated/concordium.rs
src/v2/conversions.rs
src/v2/generated/concordium.v2.rs
src/v2/mod.rs
src/v2/proto_schema_version.rs

Introduces changes needed for genesis-creator to support P6
Related to https://github.com/Concordium/concordium-misc-tools/pull/51
- Introduce `ChainParametersV2` struct for protocol version 6.
- Introduce generic `gas_reward` in `RewardParametersSkeleton` for supporting different versions of GASRewards.

Types for P6 GenesisData

---

CHANGELOG.md
src/cis0.rs
src/cis2/mod.rs
src/contract_client.rs
src/lib.rs
src/types/smart_contracts.rs

Restructure cis2 client to reduce code duplication.
- Introduce a generic "contractclient" that has some helpers for sending transactions/invoking view functions.
- Use the new client in Cis2Contract to reduce code duplication.

Refactor contract clients in preparation for CIS4.

---

CHANGELOG.md
Cargo.toml
examples/balance-summary.rs
examples/basic-test.rs
examples/collisions.rs
examples/create-initial-accounts.rs
examples/init-update-contract.rs
examples/list-account-balances.rs
examples/list-account-creations.rs
examples/list-all-transactions.rs
examples/list-initial-accounts.rs
examples/protocol-updates.rs
examples/send-transfer.rs
examples/total-stake.rs
examples/transfer-to-accounts.rs
examples/update-exchange-rate.rs
examples/v2_traverse_all_transactions.rs
src/endpoints.rs

Bump versions for release, mark V1 client as deprecated.

Mark the V1 client as deprecated.

---

CHANGELOG.md
examples/v2_get_first_block_epoch.rs
src/v2/mod.rs

Solve https://github.com/Concordium/concordium-rust-sdk/issues/118
Support for `GetFirstBlockEpoch` in the v2 client.

Implement support for `GetFirstBlockEpoch`.

---

CHANGELOG.md
Cargo.toml

Bump concordium-base and SDK version to fix web3id attribute timestamp parsing.

Fix web3id attribute parsing

---

CHANGELOG.md
examples/v2_get_bakers_reward_period.rs
src/types/mod.rs
src/v1/generated/concordium.rs
src/v2/conversions.rs
src/v2/generated/concordium.v2.rs
src/v2/mod.rs
src/v2/proto_schema_version.rs

Solve https://github.com/Concordium/concordium-rust-sdk/issues/107

Bakers reward period

---

CHANGELOG.md
src/cis4.rs
src/contract_client.rs

Add helper methods to contract clients that only construct transactions, leaving sending to the client.
This is useful in cases where transactions have to be resubmitted in case of failure (e.g., network failure).
It came up in the work on the some-issuer service.

Add helper methods to construct transactions in contract clients.

---

.github/workflows/build-and-test.yaml
src/v2/mod.rs

Fixes the warnings when running `cargo doc` and adds a lint to the Github actions.
Fixes a comment and adds the lint.

Fix doc warnings and add lint

---

CHANGELOG.md
Cargo.toml
examples/v2_dry_run.rs
src/types/smart_contracts.rs
src/v1/generated/concordium.rs
src/v2/conversions.rs
src/v2/dry_run.rs
src/v2/generated/concordium.v2.rs
src/v2/mod.rs
src/v2/proto_schema_version.rs

Expose the dry run GRPC endpoint in the API.
- Implement a `DryRun` struct that encapsulates a dry-run session and exposes each of the operations in a convenient fashion.
- A simple example using the dry run endpoint.

Add dry-run support

---

CHANGELOG.md
src/types/mod.rs
src/v2/mod.rs

Make it easier to retrieve transactions and check their signatures when retrieveing them from the chain.

Add helpers to retrieve transactions and check their signatures from the chain

---

CHANGELOG.md
src/indexer.rs
src/types/mod.rs

Add an additional indexer to index both normal and special events.
Remove obsolete JSON serialization of blocksummary. Not needed since V1 API has been removed.

Add indexer for all transaction outcomes and special outcomes.

---

CHANGELOG.md
Cargo.toml
examples/v2_dry_run.rs
examples/v2_invoke_instance.rs
src/cis0.rs
src/contract_client.rs
src/types/smart_contracts.rs
src/v2/conversions.rs
src/v2/dry_run.rs
src/v2/mod.rs

Make it easier to dry run + send update transaction in the common cases.
- Make the `energy` field of ContractContext optional.
- Add `dry_run_update` and `dry_run_update_raw` methods to the contract client, with associated types.

Add new convenience methods to the contract client for sending contract updates

---

src/v2/mod.rs

Documentation was missing and could be improved
Updated documentation

FinalizedStream documentation

---

CHANGELOG.md
Cargo.toml
README.md

Prepare for release of Rust SDK version 5.0.0

Prepare for release of 5.0.0

---

CHANGELOG.md
src/v2/conversions.rs

- Add constructor for token address type
Support for `Protocol Version 8` has already been merged into `main` but we need to rebase this PR:
https://github.com/Concordium/concordium-rust-sdk/pull/218/files
https://github.com/Concordium/concordium-rust-sdk/pull/217/files

Add constructor to cis2 tokenAddress type

---

src/types/mod.rs

Depends on: https://github.com/Concordium/concordium-base/pull/589
Support the chain parameters for protocol version 8, required by the genesis tool.
- Add `ChainParametersV3`.
- Update base.

Support chain parameters for P8.

---

CHANGELOG.md
examples/update-validator-score-param.rs
src/types/queries.rs
src/v2/conversions.rs

Add the validator score parameters to `NextSequenceNumbers`.
- Example for updating the validator score parameters.
- Add `validator_score_parameters` to `NextUpdateSequenceNumbers`.
- Fix conversion of `NextUpdateSequenceNumbers`, using the de

Support validator score parameters sequence number.

---

CHANGELOG.md

Add getter function `reward_period_epochs` to access the field in the struct `RewardPeriodLength`.

Update submodule link

---

CHANGELOG.md
src/types/smart_contracts.rs

Add helper method to parse the inner bytestring contained within ReturnValue instances. Fixes #208.
_Remove if not applicable.

add parse method for wrapped bytestring of ReturnValue

---

CHANGELOG.md
src/constants.rs

Genesis block hashes for testnet/mainnet. Fixes #209 (at least for the rust sdk).
_Remove if not applicable.

Add genesis block hash constants for testnet/mainnet.

---

CHANGELOG.md
Cargo.toml
src/indexer.rs

To be able to pass the processor config to a tokio task it needs to be send.

Ensure ProcessorConfig is Send

---

examples/v2_get_token_info.rs
examples/v2_get_token_list.rs
src/lib.rs
src/protocol_level_tokens/mod.rs
src/protocol_level_tokens/token_account_info.rs
src/protocol_level_tokens/token_info.rs
src/types/mod.rs
src/v2/conversions.rs
src/v2/mod.rs

- Export `protocol_level_tokens` module from the rust sdk reexporting the types from `concordium_base`
- Move related grpc conversion code into this module for better organization.

Implement Client::get_token_info and Client::get_token_list

---

Cargo.toml

This was only fixed to prevent increasing the MSRV, now that we are at 1.81, there is no need to fix it.

Remove fixed base64ct version

---

README.md

Remove description of old v1 gRPC api
Removed from README.md

remove description of v1 api

---

CHANGELOG.md
src/protocol_level_tokens/token_account_info.rs
src/v2/generated/concordium.v2.plt.rs
src/v2/proto_schema_version.rs

Closes [COR-1496](https://linear.app/concordium/issue/COR-1496/update-rust-sdk)
Revises `TokenAccountState` to have a `module_state` (CBOR) field instead of the `member_allow_list` and `member_deny_list` fields.
- Update `TokenAccountState`
- Add `decode_module_state` for decoding the CBOR data.

CBOR Representation of PLT Account State

---

src/types/mod.rs
src/v2/conversions.rs

Related to: https://github.com/Concordium/concordium-base/pull/681
1. Alignment:
The `Generic` on the `RejectReason` in the haskell code base
https://github.com/Concordium/concordium-base/blob/plt/haskell-src/Concordium/Types/Execution.hs#L2849
generates JSON types as follows.
```
{
"tag":"TokenGovernanceTransactionFailed"
"contents": ...
}
```
The rust code is align now by using `#[serde(tag = "tag", content = "contents")]` on the `RejectReason` type.
2. Alignment:
Variant `TokenModule` was renamed to `TokenGovernanceTransactionFailed`/`TokenHolderTransactionFailed`.
3. Alignment:
```
UnauthorizedTokenGovernance {
token_id: protocol_level_tokens::TokenId,
},
```
was changed to 
```
UnauthorizedTokenGovernance(protocol_level_tokens::TokenId)
```

Serialization alignments (COR-1536)

---

CHANGELOG.md
examples/plt-token-client.rs
src/protocol_level_tokens/token_client.rs

The mint/burn methods would benefit from receiving singular `TokenAmount` instead of `Vec<TokenAmount>`, both from performance and user experience perspectives.
The mint/burn methods now accept singular `TokenAmount` instead of `Vec<TokenAmount>`.

COR-1664 Token Client mint/burn signature change

---

CHANGELOG.md
examples/protocol-updates.rs
src/types/queries.rs
src/v2/conversions.rs

Ref COR-1717
- Introduce `ProtocolVersionInt` newtype, wrapping the `u64` representation of the `ProtocolVersion`. This type is forward-compatible, meaning future protocol versions can be represented using this type.
- Change type for field `protocol_version` in struct `BlockInfo` and `ConsensusInfo` to `ProtocolVersionInt` making these types forward-compatible.

Make BlockInfo and ConsensusInfo forward-compatible

---

Cargo.toml
src/protocol_level_tokens/token_account_info.rs
src/protocol_level_tokens/token_client.rs
src/types/mod.rs

Adding the unit tests for the `validate_transfer` method of the `TokenClient`.
- Added unit testing for `validate_transfer`.
- Added `#[derive(Clone)]` to the `AccountToken`, `AccountTokenState`.

COR-1665 `TokenClient`'s `validate_transfer` test

---

CHANGELOG.md
examples/list-all-transactions.rs
examples/transfer-indexer.rs
examples/v2_get_account_info.rs
src/contract_client.rs
src/indexer.rs
src/types/mod.rs
src/types/summary_helper.rs
src/v2/conversions.rs
src/v2/upward.rs

Make `AccountTransactionDetails` forward-compatible
Ref COR-1717
- Wrap with `Upward` for field `effects` in `AccountTransactionDetails`, making the type forward-compatible in the case of a new effect being introduced.

Forward-compatible: AccountTransactionDetails

---

CHANGELOG.md
src/v2/conversions.rs
src/v2/mod.rs

Ref COR-1717.
- Wrap `BlockItem` in return type of `get_block_items` and `get_finalized_block_items`.

Make `get_block_items` and `get_finalized_block_item` forward-compatible

---

CHANGELOG.md
src/types/queries.rs
src/v2/conversions.rs
src/v2/upward.rs

Ref COR-1717.
- Wrap field `effect` in `PendingUpdate` in `Upward`, ensuring new unknown update effects does not cause query to fail

Add `Upward` wrapper for field `effect` in `PendingUpdate`

---

.github/workflows/build-and-test.yaml
rust-toolchain.toml

Use rust-toolchain.toml to specify Rust version. Means that developers get same result as CI, including those who run examples. See https://linear.app/concordium/issue/COR-1757/rust-sdk-when-compiling-a-rusk-sdk-command-warnings-are-observed

rust toolchain.toml

---

CHANGELOG.md
src/protocol_level_tokens/token_client.rs
src/v2/conversions.rs

Ref COR-1717.
Delay the deserialization of payload in `UpdateInstruction` in Rust.
This means future payload variants will not cause errors until attempting to deserialize it, and therefore information such as the effective time can still be read without knowing the exact payload type.
Most of the changes are in the PR for base:
Related base PR: https://github.com/Concordium/concordium-base/pull/734
- Update concordium-base and fix changes.

Delay the deserialization of payload in `UpdateInstruction` in Rust

---

CHANGELOG.md
examples/v2_get_block_transaction_events.rs
src/contract_client.rs
src/indexer.rs
src/types/mod.rs
src/types/smart_contracts.rs
src/types/summary_helper.rs
src/v2/conversions.rs
src/v2/dry_run.rs
src/v2/upward.rs

Ref COR-1717.
Closes COR-1800.
Wrap `ContractTraceElement` with `Upward` to stay forward-compatible when new variants of `ContractTraceElement` are introduced.

Forward-compatible: ContractTraceElement

---

CHANGELOG.md
examples/list-account-balances.rs
src/indexer.rs
src/types/mod.rs
src/v2/conversions.rs
src/v2/mod.rs
src/v2/upward.rs

Add residual type to `Upward` that allows up to represent unknown data with e.g. `cbor::Value`. 
This is a preparation for using the `Upward` to in CBOR data model.

upward residual type

---

src/types/queries.rs
src/v2/conversions.rs

Part of [COR-1928](https://linear.app/concordium/issue/COR-1928/transaction-logger-wallet-proxy-indexer-bug-while-processing-block-on)
Fix the conversion of `ProtocolVersionInt` when values are created from the GRPC API. The GRPC values use a 0 based enum (so 0 represents PROTOCOL_VERSION_1), so it's necessary to add 1 when converting.
- Introduce `protocol_version_int_from_enum` for `ProtocolVersionInt` that does the correct conversion.
- Use the conversion where `ProtocolVersionInt` is constructed.

Fix the conversion of ProtocolVersionInt from the GRPC.

---

CHANGELOG.md
src/v2/conversions.rs

Ref COR-1717.
Closes COR-1820.
Bubble upward for new `AccountVerifyKey` variant ensuring `AccountInfo` can still be constructed for accounts with new unknown keys.
Note that querying block items where an item contains a new variant of account verify key will still fail, fixing this seems tricky so will not be part of this PR and probably not this project.

Bubble upward for new AccountVerifyKey variant for AccountInfo
