Concordium/concordium-rust-sdk

- src/constants.rs
- src/internal.rs
- src/types/mod.rs
- src/types/summary_helper.rs
- src/types/transactions.rs
Add transfers with memos,.
Support new transaction types and events.
> Add transfers with memos to supported transactiosn.

- examples/list-account-balances.rs
- src/endpoints.rs
- src/internal.rs
- src/types/mod.rs
- src/types/summary_helper.rs
- src/types/transactions.rs
Only internal symbols, comments, and strings are replaced so far.
- Change internal references to GTU to CCD.
> Update internal references to GTU to CCD

- src/endpoints.rs
- src/types/transactions.rs
Add some utilities to make transaction construction easier.
Add a notion of a pre-account-transaction, which contains the data of the transaction without the signatures.
Add a send_raw_account_transaction helper to be able to send transactions that have been constructed elsewhere.
> Add prepared transactions and the ability to send raw ones.

- CHANGELOG.md
- src/endpoints.rs
- src/types/basic.rs
A few helper methods for common wait functionality. These are needed in many examples so it is best to avoid the repetition.
> A few helper methods for common wait functionality.

- src/types/smart_contracts.rs
Fix deserial of InvokeContractResult
- Change tag for InvokeContractResult failure
> Fix deserial for InvokeContractResult

- CHANGELOG.md
- Cargo.toml
- src/cis2/mod.rs
- src/cis2/types.rs
- src/endpoints.rs
- src/lib.rs
- src/types/smart_contracts.rs
- src/types/transactions.rs
Include types and functions for interacting with a CIS2 smart contract.
Closes #23 
- Add a cis2 module containing types and a wrapper struct for interacting with CIS2 smart contracts.
- Update `concordium-contracts-common`
> Cis2 functions

- CHANGELOG.md
- Cargo.toml
Expose contract serialization macros
https://github.com/Concordium/concordium-rust-smart-contracts/issues/146
- Update `concordium-contracts-common`.
> Expose contract serialization macros

- .github/workflows/build-and-test.yaml
- src/cis2/types.rs
- src/types/mod.rs
Add a few helper methods, bump tonic & tokio, cleanup unused event.
> Add a few helpers, cleanup unused event.

- examples/init-update-contract.rs
Add an example that shows how to initialise and update a smart contract.
- Add example
> Add example that initializes and updates contract

- src/cis2/types.rs
Add some `Into` implementations where they make sense to make it easier to use the cis2 types.
> Make it easier to use cis2 types.

- src/types/basic.rs
- src/types/mod.rs
Support the genesis creator tools. https://github.com/Concordium/concordium-misc-tools/pull/6/
- Add some documentation
- bump base
- Add a number of instances related to JSON/Toml parsing.
> Add missing serialization, other, instances to various types.

- examples/v2_networkdumps.rs
- src/v2/generated.rs
- src/v2/mod.rs
Expose DumpStart and DumpStop.
> network dump exposed

- examples/v2_shutdown.rs
- src/v2/generated.rs
- src/v2/mod.rs
Expose `shutdown` in the rust sdk and added an associated example. 
> Grpc2 shutdown

- CHANGELOG.md
- Cargo.toml
- examples/v2_list_cis2_contracts.rs
- src/cis0.rs
- src/cis2/mod.rs
- src/cis2/types.rs
- src/lib.rs
- src/types/mod.rs
Add support for CIS0 queries, and fix some bugs in serialization of CIS2 events.
- Add CIS0 module
- Fix parsing of CIS2 events, add helper TryFrom implementation.
> Misc additions

- CHANGELOG.md
- Cargo.toml
- examples/protocol-updates.rs
The fix in contracs-common. This just bumps the submodules.
Depends on
> Fix schema's to_json for contract addresses.

- .gitmodules
- build.rs
- src/types/mod.rs
- src/v2/conversions.rs
Move GRPC2 type definitions to concordium-base so that we don't have to duplicate generation and conversion both in the node and in the client.
As a result concordium-base now has the grpc-api as a submodule. Consequently this submodule is removed as a direct submodule from the sdk.
> Move grpc-api submodule to concordium-base.

- CHANGELOG.md
- examples/v2_get_instances_stats.rs
- src/types/mod.rs
- src/types/smart_contracts.rs
Add a new helper that helps in dry-running contracts before sending transactions.
> Minor smart contract helpers.

- Cargo.toml
- src/smart_contracts/mod.rs
Bump concordium-base after renaming wasm-chain-integraiton.
> Bump base after renaming wasm-chain-integration.

- CHANGELOG.md
- Cargo.toml
- examples/v2_get_account_info.rs
- examples/v2_get_pool_delegators_reward_period.rs
- examples/v2_get_pool_info.rs
- src/v2/mod.rs
Add a number of helper methods.
Specifically the find_instance... is needed in the relayer.
> Add a number of helper methods for finding blocks.

- src/endpoints.rs
- src/v2/mod.rs
Quality of life improvements..
- re-export definitions used in functions so that users don't have to explicitly depend on tonic.
- helpers for analyzing client errors.
> Add additional quality of life improvements.

- .github/workflows/build-and-test.yaml
- .github/workflows/docs.yaml
- CHANGELOG.md
- Cargo.toml
- README.md
> Bump base to simplify dependencies.

- examples/v2_contract_deploy_init_update.rs
Add a simple example on how to use schemas for contract updates.
> Add example on how to use schemas with the Rust SDK.

- .github/workflows/build-and-test.yaml
- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/types/mod.rs
- src/v2/mod.rs
Bump concordium base to get access to extra helpers.
> Bump base to get extra helpers.

- CHANGELOG.md
- Cargo.toml
- examples/init-update-contract.rs
- examples/v2_contract_deploy_init_update.rs
Bump concordium-base, prepare for release.
> Bump concordium base, prepare for release.

- Cargo.toml
Enable encryption feature
- Enable encryption feature
> Enable encryption feature

- .github/workflows/build-and-test.yaml
- CHANGELOG.md
- Cargo.toml
- examples/block-stats.rs
- examples/find-account.rs
- examples/list-number-account-transactions.rs
- examples/v2_get_block_info.rs
- src/postgres.rs
- src/v2/mod.rs
Improvements to the SDK to make use of the new node API.
> Block height improvements

- Cargo.toml
- src/internal.rs
- src/web3id.rs
Add functionality for interacting with credential storage contract, storing and retrieving.
> Add operations for credential storage related to web3id.

- CHANGELOG.md
- src/types/mod.rs
- src/v1/generated/concordium.rs
- src/v2/conversions.rs
- src/v2/generated/concordium.v2.rs
- src/v2/proto_schema_version.rs
Solves https://github.com/Concordium/concordium-rust-sdk/issues/109
> Amend PoolCurrentPaydayinfo with commission rates.

- .github/workflows/build-and-test.yaml
Attempt to simplify and fix CI.
> Attempt to fix CI.

- CHANGELOG.md
- Cargo.toml
Bump version to 3.1.0 to prepare for release.
> Prepare for release of 3.1.0.

- CHANGELOG.md
- src/types/mod.rs
- src/v2/mod.rs
> Extract contract updates

- examples/v2_create_initial_accounts.rs
> Create directory when running create-initial-accounts.

- CHANGELOG.md
- src/types/mod.rs
- src/v2/conversions.rs
- src/v2/generated/concordium.v2.rs
- src/v2/proto_schema_version.rs
Add support for protocol version P7.
- Update concordium-base dependency.
- Add handling for P7.
> Support Protocol P7

- CHANGELOG.md
Enable debugging support in smart contract execution engine.
Depends on
> Update base to get access to debugging support in the execution engine.

- .github/workflows/build-and-test.yaml
- CHANGELOG.md
- Cargo.toml
- examples/transfer-indexer.rs
- src/indexer.rs
- src/types/mod.rs
> Indexer example and utils

- CHANGELOG.md
- src/cis2/mod.rs
- src/cis3.rs
- src/lib.rs
Closes #189. Depends on https://github.com/Concordium/concordium-base/pull/526
> Cis3 support

- CHANGELOG.md
- Cargo.toml
> Release version 6.0.0.

- CHANGELOG.md
- src/indexer.rs
Introduce generalized process events taking an abstract stream.
> Add support of processing streams in ProcessorConfig

- CHANGELOG.md
- src/indexer.rs
Allow stopping during error timeout
> Check stop_signal in wait_after_fail for ProcessorConfig

- src/v2/conversions.rs
Update concordium-base and fix change due to comments in https://github.com/Concordium/concordium-base/pull/626
> PLT: Update base

- Cargo.toml
> Update concordium-base ref

- CHANGELOG.md
- Cargo.toml
> release9.0.2

- Cargo.toml
_Describe the purpose of the pull request, link to issue describing the problem, etc.
> update base version

- CHANGELOG.md
- src/types/mod.rs
- src/v2/conversions.rs
Ref COR-1717.
Forward-compatible: `CommonRewardData`
- Use `ProtocolVersionInt` in `CommonRewardData`.
> Forward-compatible: `CommonRewardData`

- CHANGELOG.md
- Cargo.toml
_Describe the purpose of the pull request, link to issue describing the problem, etc.
_Remove if not applicable.
> Make major release

- CHANGELOG.md
- src/cis2/mod.rs
- src/cis3.rs
- src/indexer.rs
- src/types/mod.rs
- src/v2/upward.rs
- src/web3id.rs
Related to: https://github.com/Concordium/concordium-misc-tools/pull/257
_Remove if not applicable.
> Improve forward compatibility
